import React, { useEffect, useState } from 'react'
import { getAIReports } from '../services/aiReportService'
import { format } from 'date-fns'

const AIReports = () => {
  const [reports, setReports] = useState([])
  const [loading, setLoading] = useState(true)
  const [selectedReport, setSelectedReport] = useState(null)

  useEffect(() => {
    loadReports()
  }, [])

  const loadReports = async () => {
    try {
      const data = await getAIReports()
      setReports(data)
      if (data.length > 0) {
        setSelectedReport(data[0])
      }
    } catch (error) {
      console.error('Error loading reports:', error)
    } finally {
      setLoading(false)
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-indigo-600"></div>
      </div>
    )
  }

  return (
    <div className="space-y-8 animate-fade-in">
      <div>
        <h1 className="text-4xl font-bold text-gray-800 mb-2">AI Coaching Reports</h1>
        <p className="text-gray-600">Personalized insights and recommendations from AI</p>
      </div>

      {reports.length === 0 ? (
        <div className="card text-center py-12">
          <div className="text-6xl mb-4">🤖</div>
          <h2 className="text-2xl font-bold text-gray-800 mb-2">No Reports Yet</h2>
          <p className="text-gray-600 mb-6">
            Your first AI coaching report will be generated automatically every Sunday.
            Keep tracking your habits to receive personalized insights!
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Reports List */}
          <div className="lg:col-span-1 space-y-4">
            <h2 className="text-xl font-bold text-gray-800 mb-4">All Reports</h2>
            {reports.map((report) => (
              <button
                key={report.id}
                onClick={() => setSelectedReport(report)}
                className={`w-full text-left card transition-all ${
                  selectedReport?.id === report.id
                    ? 'ring-2 ring-indigo-500 bg-indigo-50'
                    : 'hover:scale-105'
                }`}
              >
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm font-semibold text-gray-700">
                    {format(new Date(report.startDate), 'MMM dd')} - {format(new Date(report.endDate), 'MMM dd')}
                  </span>
                  <span className="text-xs text-gray-500">
                    {format(new Date(report.createdAt), 'MMM dd, yyyy')}
                  </span>
                </div>
                <p className="text-xs text-gray-600 line-clamp-2">
                  {report.feedbackText.substring(0, 100)}...
                </p>
              </button>
            ))}
          </div>

          {/* Selected Report Detail */}
          {selectedReport && (
            <div className="lg:col-span-2">
              <div className="card bg-gradient-to-br from-indigo-50 to-purple-50 border-indigo-200 animate-slide-up">
                <div className="mb-6">
                  <div className="flex items-center justify-between mb-4">
                    <div>
                      <h2 className="text-3xl font-bold text-gray-800 mb-2">🤖 AI Coaching Report</h2>
                      <p className="text-gray-600">
                        {format(new Date(selectedReport.startDate), 'MMMM dd')} - {format(new Date(selectedReport.endDate), 'MMMM dd, yyyy')}
                      </p>
                    </div>
                    <div className="text-sm text-gray-500">
                      Generated: {format(new Date(selectedReport.createdAt), 'MMM dd, yyyy')}
                    </div>
                  </div>
                </div>

                <div className="bg-white/70 rounded-xl p-6 border border-white/50 shadow-lg">
                  <div className="prose max-w-none">
                    <p className="text-gray-700 whitespace-pre-line leading-relaxed text-lg">
                      {selectedReport.feedbackText}
                    </p>
                  </div>
                </div>

                <div className="mt-6 flex items-center space-x-2 text-sm text-gray-600">
                  <span>✨</span>
                  <span>Generated by AI using local Ollama models</span>
                </div>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Info Card */}
      <div className="card bg-blue-50 border-blue-200">
        <div className="flex items-start space-x-4">
          <div className="text-3xl">ℹ️</div>
          <div>
            <h3 className="font-semibold text-gray-800 mb-2">About AI Reports</h3>
            <p className="text-gray-700 text-sm">
              Your AI coaching reports are automatically generated every Sunday at 9 AM. 
              They analyze your weekly habit performance, identify patterns, and provide 
              personalized recommendations to help you build better habits. All AI processing 
              happens locally using Ollama - your data never leaves your machine.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default AIReports

